import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuthStore } from '../store';
import { api } from '../api';
import { FileText, CheckCircle, Clock, AlertCircle, Check, X, Phone, Mail, User as UserIcon, MessageSquare } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function Orders() {
  const [orders, setOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const user = useAuthStore((state) => state.user);

  useEffect(() => {
    fetchOrders();
  }, []);

  const fetchOrders = () => {
    api.getOrders().then((data) => {
      setOrders(data);
      setLoading(false);
    });
  };

  const handleStatusChange = async (id: number, status: string) => {
    try {
      await api.updateOrderStatus(id, { status });
      fetchOrders();
    } catch (err: any) {
      alert(err.message);
    }
  };

  const handlePaymentStatusChange = async (id: number, payment_status: string) => {
    try {
      await api.updateOrderStatus(id, { payment_status });
      fetchOrders();
    } catch (err: any) {
      alert(err.message);
    }
  };

  const handleQuoteAction = async (id: number, action: 'approve' | 'decline') => {
    try {
      await api.quoteAction(id, action);
      alert(`Quote ${action === 'approve' ? 'approved' : 'declined'} successfully.`);
      fetchOrders();
    } catch (err: any) {
      alert(err.message);
    }
  };

  const generateInvoice = (order: any) => {
    const doc = new jsPDF();
    
    // Header with Logo
    if (order.logo_url) {
      try {
        doc.addImage(order.logo_url, 'PNG', 14, 10, 30, 30);
      } catch (e) {
        console.error("Could not add logo to PDF", e);
      }
    }

    // Vendor Details (Top Right)
    doc.setFontSize(20);
    doc.setTextColor(0, 179, 164); // Teal
    doc.text(order.vendor_name, 200, 20, { align: 'right' });
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    let vendorY = 28;
    if (order.vendor_address) {
      doc.text(order.vendor_address, 200, vendorY, { align: 'right' });
      vendorY += 5;
    }
    if (order.vendor_phone) {
      doc.text(`Phone: ${order.vendor_phone}`, 200, vendorY, { align: 'right' });
      vendorY += 5;
    }
    if (order.vendor_tax_id) {
      doc.text(`Tax ID: ${order.vendor_tax_id}`, 200, vendorY, { align: 'right' });
    }

    // Invoice Header Info
    doc.setFontSize(24);
    doc.setTextColor(0);
    doc.text('INVOICE', 14, 55);
    
    doc.setFontSize(10);
    doc.text(`Invoice #: INV-${order.id}`, 14, 65);
    doc.text(`Date: ${new Date(order.created_at).toLocaleDateString()}`, 14, 70);
    doc.text(`Payment Method: ${order.payment_method}`, 14, 75);
    doc.text(`Payment Status: ${order.payment_status.toUpperCase()}`, 14, 80);

    // Customer Contact Info (Name, Email, Tel)
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('BILL TO (CUSTOMER):', 14, 95);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${order.customer_name || user?.name || 'Valued Customer'}`, 14, 102);
    if (order.customer_email) doc.text(`Email: ${order.customer_email}`, 14, 108);
    if (order.customer_phone) doc.text(`Tel: ${order.customer_phone}`, 14, 114);

    const startTableY = order.customer_phone ? 122 : 112;

    const tableData = order.items.map((item: any) => [
      item.product_name,
      item.quantity,
      `EC $${item.price.toFixed(2)}`,
      `${item.vat_percent}%`,
      `EC $${(item.price * item.quantity * (1 + item.vat_percent / 100)).toFixed(2)}`
    ]);

    autoTable(doc, {
      startY: startTableY,
      head: [['Item', 'Qty', 'Unit Price', 'VAT', 'Total']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [0, 179, 164] },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;
    
    // Totals
    const subtotal = order.items.reduce((sum: number, item: any) => sum + (item.price * item.quantity), 0);
    const vatTotal = order.total - subtotal;

    doc.setFontSize(10);
    doc.text('Subtotal:', 140, finalY);
    doc.text(`EC $${subtotal.toFixed(2)}`, 200, finalY, { align: 'right' });
    
    doc.text('VAT Total:', 140, finalY + 7);
    doc.text(`EC $${vatTotal.toFixed(2)}`, 200, finalY + 7, { align: 'right' });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Grand Total:', 140, finalY + 17);
    doc.text(`EC $${order.total.toFixed(2)}`, 200, finalY + 17, { align: 'right' });

    // Footer
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150);
    doc.text('Generated by Ordely - The Caribbean Business Platform', 105, 285, { align: 'center' });

    doc.save(`Ordely_Invoice_${order.id}.pdf`);
  };

  const generateQuote = (order: any) => {
    const doc = new jsPDF();
    
    // Header with Logo
    if (order.logo_url) {
      try { doc.addImage(order.logo_url, 'PNG', 14, 10, 30, 30); } catch (e) {}
    }

    // Vendor Details (Top Right)
    doc.setFontSize(20);
    doc.setTextColor(0, 179, 164);
    doc.text(order.vendor_name, 200, 20, { align: 'right' });
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    let vendorY = 28;
    if (order.vendor_address) { doc.text(order.vendor_address, 200, vendorY, { align: 'right' }); vendorY += 5; }
    if (order.vendor_phone) { doc.text(`Phone: ${order.vendor_phone}`, 200, vendorY, { align: 'right' }); vendorY += 5; }
    if (order.vendor_tax_id) { doc.text(`Tax ID: ${order.vendor_tax_id}`, 200, vendorY, { align: 'right' }); }

    // Quote Info
    doc.setFontSize(24);
    doc.setTextColor(0);
    doc.text('OFFICIAL QUOTE', 14, 55);
    
    doc.setFontSize(10);
    doc.text(`Quote #: Q-${order.id}`, 14, 65);
    doc.text(`Date: ${new Date(order.created_at).toLocaleDateString()}`, 14, 70);
    doc.text(`Valid Until: ${new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}`, 14, 75);

    // Customer Contact Info (Name, Email, Tel)
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('PREPARED FOR (CUSTOMER):', 14, 90);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${order.customer_name || user?.name || 'Valued Customer'}`, 14, 97);
    if (order.customer_email) doc.text(`Email: ${order.customer_email}`, 14, 103);
    if (order.customer_phone) doc.text(`Tel: ${order.customer_phone}`, 14, 109);

    const startTableY = order.customer_phone ? 118 : 108;

    const tableData = order.items.map((item: any) => [
      item.product_name,
      item.quantity,
      `EC $${item.price.toFixed(2)}`,
      `${item.vat_percent}%`,
      `EC $${(item.price * item.quantity * (1 + item.vat_percent / 100)).toFixed(2)}`
    ]);

    autoTable(doc, {
      startY: startTableY,
      head: [['Item', 'Qty', 'Unit Price', 'VAT', 'Total']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [0, 179, 164] },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;
    
    const subtotal = order.items.reduce((sum: number, item: any) => sum + (item.price * item.quantity), 0);
    const vatTotal = order.total - subtotal;

    doc.setFontSize(10);
    doc.text('Subtotal:', 140, finalY);
    doc.text(`EC $${subtotal.toFixed(2)}`, 200, finalY, { align: 'right' });
    
    doc.text('VAT Total:', 140, finalY + 7);
    doc.text(`EC $${vatTotal.toFixed(2)}`, 200, finalY + 7, { align: 'right' });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Grand Total:', 140, finalY + 17);
    doc.text(`EC $${order.total.toFixed(2)}`, 200, finalY + 17, { align: 'right' });

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150);
    doc.text('Generated by Ordely - The Caribbean Business Platform', 105, 285, { align: 'center' });

    doc.save(`Ordely_Quote_${order.id}.pdf`);
  };

  if (loading) return <div className="text-center py-20">Loading orders...</div>;

  return (
    <div>
      <h2 className="text-3xl font-bold text-slate-900 mb-8">{user?.role === 'vendor' ? 'Customer Orders & Quotes' : 'My Orders & Quotes'}</h2>
      
      {orders.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-3xl shadow-sm border border-slate-100">
          <p className="text-slate-500">No orders found.</p>
        </div>
      ) : (
        <div className="space-y-6">
          {orders.map((order) => {
            const isQuotePending = order.status === 'quote_pending';
            const isQuoteApproved = order.status === 'quote_approved';
            const isQuoteDeclined = order.status === 'quote_declined';

            return (
              <div key={order.id} className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 space-y-6">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center pb-6 border-b border-slate-100 gap-4">
                  <div>
                    <div className="flex items-center gap-3">
                      <h3 className="text-lg font-bold text-slate-900">Order #{order.id}</h3>
                      {isQuotePending && (
                        <span className="bg-amber-100 text-amber-800 text-xs px-2.5 py-1 rounded-md font-bold flex items-center gap-1">
                          <AlertCircle className="w-3.5 h-3.5 text-amber-600" />
                          Quote Approval Needed
                        </span>
                      )}
                      {isQuoteApproved && (
                        <span className="bg-emerald-100 text-emerald-800 text-xs px-2.5 py-1 rounded-md font-bold flex items-center gap-1">
                          <CheckCircle className="w-3.5 h-3.5 text-emerald-600" />
                          Quote Approved
                        </span>
                      )}
                      {isQuoteDeclined && (
                        <span className="bg-rose-100 text-rose-800 text-xs px-2.5 py-1 rounded-md font-bold flex items-center gap-1">
                          <X className="w-3.5 h-3.5 text-rose-600" />
                          Quote Declined
                        </span>
                      )}
                    </div>
                    <p className="text-sm text-slate-500 mt-1">
                      {new Date(order.created_at).toLocaleString()} • {user?.role === 'vendor' ? `Customer: ${order.customer_name}` : `Vendor: ${order.vendor_name}`}
                    </p>
                  </div>

                  <div className="flex items-center gap-3">
                    <span className={`px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1 ${
                      order.status === 'completed' ? 'bg-green-100 text-green-700' :
                      isQuotePending ? 'bg-amber-100 text-amber-700' :
                      isQuoteApproved ? 'bg-teal-100 text-teal-700' :
                      isQuoteDeclined ? 'bg-rose-100 text-rose-700' :
                      'bg-orange-100 text-orange-700'
                    }`}>
                      {order.status === 'completed' ? <CheckCircle className="w-4 h-4" /> : <Clock className="w-4 h-4" />}
                      {order.status.replace('_', ' ').toUpperCase()}
                    </span>
                    <span className={`px-3 py-1 rounded-full text-xs font-bold ${order.payment_status === 'paid' ? 'bg-teal-100 text-teal-700' : 'bg-slate-100 text-slate-700'}`}>
                      {order.payment_status.toUpperCase()}
                    </span>
                  </div>
                </div>

                {/* Customer / Vendor Details Summary Box */}
                <div className="bg-slate-50 rounded-xl p-4 text-xs text-slate-600 flex flex-wrap items-center justify-between gap-4 border border-slate-100">
                  <div className="flex flex-wrap items-center gap-4">
                    <div className="flex items-center gap-2">
                      <UserIcon className="w-4 h-4 text-teal-600" />
                      <span className="font-semibold text-slate-900">{user?.role === 'vendor' ? order.customer_name : order.vendor_name}</span>
                    </div>
                    {order.customer_email && user?.role === 'vendor' && (
                      <div className="flex items-center gap-1.5">
                        <Mail className="w-3.5 h-3.5 text-slate-400" />
                        <span>{order.customer_email}</span>
                      </div>
                    )}
                    {order.customer_phone && user?.role === 'vendor' && (
                      <div className="flex items-center gap-1.5">
                        <Phone className="w-3.5 h-3.5 text-teal-600" />
                        <span className="font-medium text-slate-900">{order.customer_phone}</span>
                      </div>
                    )}
                  </div>

                  {/* Messaging Trigger */}
                  {user?.role === 'vendor' ? (
                    <Link
                      to={`/messages?userId=${order.customer_id}`}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-teal-600 hover:bg-teal-700 text-white font-semibold transition-colors shadow-xs"
                    >
                      <MessageSquare className="w-3.5 h-3.5" />
                      <span>Message Customer</span>
                    </Link>
                  ) : (
                    order.vendor_user_id && (
                      <Link
                        to={`/messages?userId=${order.vendor_user_id}`}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-teal-600 hover:bg-teal-700 text-white font-semibold transition-colors shadow-xs"
                      >
                        <MessageSquare className="w-3.5 h-3.5" />
                        <span>Message Vendor</span>
                      </Link>
                    )
                  )}
                </div>

                {/* Quote Action Box for Customer */}
                {user?.role === 'customer' && isQuotePending && (
                  <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                    <div className="space-y-1">
                      <h4 className="text-sm font-bold text-amber-900 flex items-center gap-1.5">
                        <AlertCircle className="w-4 h-4 text-amber-600" />
                        Quote Approval Required
                      </h4>
                      <p className="text-xs text-amber-800">
                        Please review the quote details below. You must approve the quote before the vendor can process and fulfill your order.
                      </p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <button
                        onClick={() => handleQuoteAction(order.id, 'approve')}
                        className="bg-teal-600 hover:bg-teal-700 text-white text-xs font-bold px-4 py-2 rounded-lg transition-colors flex items-center gap-1.5 shadow-sm"
                      >
                        <Check className="w-4 h-4" />
                        Approve Quote
                      </button>
                      <button
                        onClick={() => handleQuoteAction(order.id, 'decline')}
                        className="bg-white hover:bg-rose-50 text-rose-600 border border-rose-200 text-xs font-bold px-3 py-2 rounded-lg transition-colors flex items-center gap-1.5"
                      >
                        <X className="w-4 h-4" />
                        Decline
                      </button>
                    </div>
                  </div>
                )}

                {/* Notice for Vendor if Quote Pending */}
                {user?.role === 'vendor' && isQuotePending && (
                  <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-800 flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-amber-600 shrink-0" />
                    <span>Customer has not approved this quote yet. Order status cannot be moved to processing or completed until approved.</span>
                  </div>
                )}

                <div className="space-y-3">
                  {order.items.map((item: any) => (
                    <div key={item.id} className="flex justify-between items-center text-sm">
                      <span className="font-medium text-slate-700">{item.quantity} × {item.product_name}</span>
                      <span className="text-slate-500 font-mono">EC ${(item.price * item.quantity * (1 + item.vat_percent / 100)).toFixed(2)}</span>
                    </div>
                  ))}
                </div>

                <div className="flex flex-col md:flex-row justify-between items-center pt-4 border-t border-slate-100 gap-4">
                  <div>
                    <p className="text-xs text-slate-500">Total (incl. VAT)</p>
                    <p className="text-2xl font-bold text-teal-600">EC ${order.total.toFixed(2)}</p>
                  </div>
                  
                  <div className="flex flex-wrap items-center gap-3">
                    <button
                      onClick={() => generateInvoice(order)}
                      className="flex items-center gap-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 px-3.5 py-2 rounded-lg text-xs font-bold transition-colors"
                    >
                      <FileText className="w-4 h-4 text-slate-500" />
                      Invoice PDF
                    </button>

                    <button
                      onClick={() => generateQuote(order)}
                      className="flex items-center gap-1.5 bg-teal-50 hover:bg-teal-100 text-teal-700 px-3.5 py-2 rounded-lg text-xs font-bold transition-colors"
                    >
                      <FileText className="w-4 h-4 text-teal-600" />
                      Quote PDF
                    </button>
                    
                    {user?.role === 'vendor' && (
                      <div className="flex gap-2">
                        <select
                          value={order.status}
                          onChange={(e) => handleStatusChange(order.id, e.target.value)}
                          className="bg-white border border-slate-200 text-slate-700 px-3 py-2 rounded-lg text-xs font-semibold outline-none focus:ring-2 focus:ring-teal-500"
                        >
                          <option value="quote_pending" disabled={order.status !== 'quote_pending'}>Quote Pending Approval</option>
                          <option value="quote_approved">Quote Approved</option>
                          <option value="processing" disabled={isQuotePending}>Processing</option>
                          <option value="shipped" disabled={isQuotePending}>Shipped</option>
                          <option value="completed" disabled={isQuotePending}>Completed</option>
                          <option value="cancelled">Cancelled</option>
                        </select>

                        <select
                          value={order.payment_status}
                          onChange={(e) => handlePaymentStatusChange(order.id, e.target.value)}
                          className="bg-white border border-slate-200 text-slate-700 px-3 py-2 rounded-lg text-xs font-semibold outline-none focus:ring-2 focus:ring-teal-500"
                        >
                          <option value="pending">Unpaid</option>
                          <option value="paid">Paid</option>
                        </select>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
